apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: blog-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-proxy
  template:
    metadata:
      labels:
        app: blog-proxy
    spec:
      containers:
      - name: nginx-proxy
        # يجب استخدام صورتك التي تم بناؤها (مثال: myrepo/nginx-proxy:latest)
        image: esraaeissa81/proxy:LATEST_IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 443