apiVersion: v1
kind: Service
metadata:
  name: proxy-nodeport
spec:
  selector:
    app: blog-proxy
  ports:
    - protocol: TCP
      port: 443 # المنفذ الذي يستمع عليه البروكسي داخلياً
      targetPort: 443 
      # اختياري: يمكنك تحديد NodePort معين (مثلاً 30080)، وإلا سيتم اختياره تلقائياً
      nodePort: 30443 
  type: NodePort